CREATE DATABASE assignments;

use assignments;

CREATE TABLE assignments (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    date DATETIME DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(50) NOT NULL,
	assignmentname VARCHAR(100) NOT NULL,
	unit VARCHAR(100) NOT NULL,
	duedate VARCHAR(50)
);

CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	date DATETIME DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);